### ISSUE TITLE
error run quick-start.lua

### ISSUE THREAD

**Issue by EvanDylan** [pkulchenko/ZeroBraneEduPack#5] opened 2017-04-01 08:21 UTC
thanks for your work. But something wrong was happened when i try to running the code.

quick-start.lua:55: bad argument #1 to 'format' (number has no integer representation)

**Comment by pkulchenko** [comment] 2017-04-01 17:20
@EvanDylan, thank you for the report. This looks like a duplicate of https://github.com/pkulchenko/ZeroBraneStudio/issues/722, which was already fixed in 29b6559 and will be included in the next release.

**Closed by pkulchenko** 2017-04-01 17:20 UTC
